/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_Fwlib32 */

#ifndef _Included_test_Fwlib32
#define _Included_test_Fwlib32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_Fwlib32
 * Method:    cncNull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_Fwlib32_cncNull
  (JNIEnv *, jclass);

/*
 * Class:     test_Fwlib32
 * Method:    cncStartupprocess
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncStartupprocess
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     test_Fwlib32
 * Method:    cncAllocLibHandle3
 * Signature: (Ljava/lang/String;II[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncAllocLibHandle3
  (JNIEnv *, jclass, jstring, jint, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncFreeLibHandle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncFreeLibHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_Fwlib32
 * Method:    cncExitprocess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncExitprocess
  (JNIEnv *, jclass);

/*
 * Class:     test_Fwlib32
 * Method:    cncExitthread
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncExitthread
  (JNIEnv *, jclass);

/*
 * Class:     test_Fwlib32
 * Method:    cncSetPath
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncSetPath
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     test_Fwlib32
 * Method:    cncReadParam
 * Signature: (IIII[J)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncReadParam
  (JNIEnv *, jclass, jint, jint, jint, jint, jlongArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncGetTimer
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncGetTimer
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncReadMacro
 * Signature: (III[J)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncReadMacro
  (JNIEnv *, jclass, jint, jint, jint, jlongArray);

/*
 * Class:     test_Fwlib32
 * Method:    pmcReadPmcrng
 * Signature: (IIIIII[J)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_pmcReadPmcrng
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jlongArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncDiagnoss
 * Signature: (IIII[J)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncDiagnoss
  (JNIEnv *, jclass, jint, jint, jint, jint, jlongArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncStartophis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncStartophis
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_Fwlib32
 * Method:    cncStopophis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncStopophis
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdalmhisno
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdalmhisno
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdalmhistry5
 * Signature: (IIII[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdalmhistry5
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdalmhistry5Msg
 * Signature: (IIII[C)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdalmhistry5Msg
  (JNIEnv *, jclass, jint, jint, jint, jint, jcharArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncStartomhis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncStartomhis
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_Fwlib32
 * Method:    cncStopomhis
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncStopomhis
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdomhisno
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdomhisno
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdomhistry2
 * Signature: (IIII[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdomhistry2
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdomhistry2Msg
 * Signature: (IIII[C)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdomhistry2Msg
  (JNIEnv *, jclass, jint, jint, jint, jint, jcharArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncprgName
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncprgName
  (JNIEnv *, jclass, jint, jcharArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncUpload3
 * Signature: (IIIII[C)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncUpload3
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jcharArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncrdtofs
 * Signature: (IIII[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncrdtofs
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncSysInfo
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncSysInfo
  (JNIEnv *, jclass, jint, jcharArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncRdprogdir2
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncRdprogdir2
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     test_Fwlib32
 * Method:    cncWriteOffset
 * Signature: (IIIJ)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncWriteOffset
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     test_Fwlib32
 * Method:    pmcWrpmcrng
 * Signature: (IIIIIIJ)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_pmcWrpmcrng
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     test_Fwlib32
 * Method:    cncWrmacro
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_test_Fwlib32_cncWrmacro
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
